language: node_js
sudo: false
node_js: stable
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2549ee9581a4_key -iv $encrypted_2549ee9581a4_iv  -in  .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'xsxun'
- git config --global user.email xsxuno@outlook.com
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
